(when (and (maybe-require-package 'company-go) (maybe-require-package 'flycheck) (maybe-require-package 'go-mode))
  (add-to-list 'exec-path (expand-file-name "~/.goenv/shims"))
  (add-to-list 'exec-path (expand-file-name "~/.go/bin"))
  (require 'go-mode)
  (require 'company-go)
  (add-hook 'go-mode-hook 'company-mode)
  (add-hook 'go-mode-hook 'flycheck-mode)
  (add-hook 'go-mode-hook (lambda ()
    (add-hook 'before-save-hook 'gofmt-before-save)
    (local-set-key (kbd "M-.") 'godef-jump)
    (set (make-local-variable 'company-backends) '(company-go))
    (company-mode)
    (setq indent-tabs-mode nil)
    (setq c-basic-offset 4)
    (setq tab-width 4))))
