(when (and (maybe-require-package 'ruby-electric) (maybe-require-package 'robe) (maybe-require-package 'company) (maybe-require-package 'rbenv))
  (setenv "PATH" (concat (expand-file-name "~/.rbenv/shims/ruby") (getenv "PATH")))
  (require 'rbenv)
  (setq rbenv-installation-dir "~/.rbenv")
  (require 'ruby-electric)
  (add-hook 'ruby-mode-hook '(lambda ()
    (ruby-electric-mode t)))
  (setq ruby-electric-expand-delimiters-list nil)
  (add-hook 'ruby-mode-hook 'robe-mode)
  (autoload 'robe-mode "robe" "Code navigation, documentation lookup and completion for Ruby" t nil)
  (eval-after-load 'company '(push 'company-robe company-backends))
  (add-hook 'ruby-mode-hook (lambda ()
    (company-mode)
    (setq company-auto-expand t)
    (setq company-transformers '(company-sort-by-backend-importance))
    (setq company-idle-delay 0)
    (setq company-minimum-prefix-length 1)
    (setq company-selection-wrap-around t)
    (setq completion-ignore-case t)
    (setq company-dabbrev-downcase nil)
    (global-set-key (kbd "C-M-i") 'company-complete)
    (define-key company-active-map (kbd "C-n") 'company-select-next)
    (define-key company-active-map (kbd "C-p") 'company-select-previous)
    (define-key company-active-map (kbd "C-s") 'company-filter-candidates)
    (define-key company-active-map [tab] 'company-complete-selection)
    (define-key emacs-lisp-mode-map (kbd "C-M-i") 'company-complete))))
